import React from 'react';
import "./css/Brand.css";

export default class School extends React.Component {
	constructor() {
		super();
	}
	 change(e){
		 if(e.target.innerHTML.length<10){
			let a= document.querySelectorAll(".brandmenu div");
			for(let i = 0;i<a.length;i++){
				a[i].style.color="black";
				a[i].style.backgroundColor="white";
			}
			 e.target.style.backgroundColor="#B1BEDD";
			 e.target.style.color="white";
		 }
	 }
	render() {
		return (
		<div className="content">
			<div className="brandmenu" onClick={this.change.bind(this)}>
				<div style={{backgroundColor:"#B1BEDD",color:"white"}}>商业</div>
				<div>沙龙</div>
				<div>A</div>
				<div>B</div>
				<div>C</div>
				<div>D</div>
				<div>E</div>
				<div>F</div>
				<div>G</div>
				<div>H</div>
				<div>I</div>
				<div>J</div>
				<div>K</div>
				<div>L</div>
				<div>M</div>
				<div>N</div>
				<div>O</div>
				<div>P</div>
				<div>Q</div>
				<div>R</div>
				<div>S</div>
				<div>T</div>
				<div>U</div>
				<div>V</div>
				<div>W</div>
				<div>X</div>
				<div>Y</div>
				<div>Z</div>
			</div>
			<div className="b1">
				<div className="b1-top"></div>
				<div className="b1-content">
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>祖玛珑</span><br/>
							<span>Jo Malone</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>娇兰</span><br/>
							<span>Guerlain</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>宝格丽</span><br/>
							<span>Bvlgari</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>迪奥</span><br/>
							<span>Dior</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>香奈儿</span><br/>
							<span>Chanel</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>汤姆·福特</span><br/>
							<span>Tom Ford</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>博柏利</span><br/>
							<span>Burberry</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>圣罗兰</span><br/>
							<span>YSL Yves Saint Laurent</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>古驰</span><br/>
							<span>Gucci</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>莱俪</span><br/>
							<span>Lalique</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>阿玛尼</span><br/>
							<span>Giorgio Armani</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>高田贤三</span><br/>
							<span>Kenzo</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>凯文克莱</span><br/>
							<span>Calvin Klein</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>范思哲</span><br/>
							<span>Versace</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>三宅一生</span><br/>
							<span>Issey Miyake</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>浪凡</span><br/>
							<span>Lanvin</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>纪梵希</span><br/>
							<span>Givenchy</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>蔻依</span><br/>
							<span>Chloe</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>兰蔻</span><br/>
							<span>Lancome</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>纳茜素</span><br/>
							<span>Narciso Rodriguez</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>大卫杜夫</span><br/>
							<span>Davidoff</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>安娜苏</span><br/>
							<span>Anna Sui</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>4711</span><br/>
							<span>4711</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>莫杰</span><br/>
							<span>Marc Jacobs</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>橘滋</span><br/>
							<span>Juicy Couture</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>帝门特</span><br/>
							<span>Demeter Fragrance</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>普拉达</span><br/>
							<span>Prada</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>缪缪</span><br/>
							<span>Miu Miu</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>罗意威</span><br/>
							<span>Loewe</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>雅诗兰黛</span><br/>
							<span>Estée Lauder</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>保罗史密斯</span><br/>
							<span>Paul Smith</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>宾利</span><br/>
							<span>Bentley</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>川久保玲</span><br/>
							<span>Comme des Garcons</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>D二次方</span><br/>
							<span>DSQUARED</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>桃丝熊</span><br/>
							<span>Tous</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>王薇薇</span><br/>
							<span>Vera Wang</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>万宝龙</span><br/>
							<span>Montblanc</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>蒂芙尼</span><br/>
							<span>Tiffany & Co</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>萧邦</span><br/>
							<span>Chopard</span>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		)
	}
}
