import React from 'react';
import "./css/Brand.css";

export default class School extends React.Component {
	constructor() {
		super();
	}
	 change(e){
		 if(e.target.innerHTML.length<10){
			let a= document.querySelectorAll(".brandmenu div");
			for(let i = 0;i<a.length;i++){
				a[i].style.color="black";
				a[i].style.backgroundColor="white";
			}
			 e.target.style.backgroundColor="#B1BEDD";
			 e.target.style.color="white";
		 }
	 }
	render() {
		return (
		<div className="content">
			<div className="brandmenu" onClick={this.change.bind(this)}>
				<div style={{backgroundColor:"#B1BEDD",color:"white"}}>商业</div>
				<div>沙龙</div>
				<div>A</div>
				<div>B</div>
				<div>C</div>
				<div>D</div>
				<div>E</div>
				<div>F</div>
				<div>G</div>
				<div>H</div>
				<div>I</div>
				<div>J</div>
				<div>K</div>
				<div>L</div>
				<div>M</div>
				<div>N</div>
				<div>O</div>
				<div>P</div>
				<div>Q</div>
				<div>R</div>
				<div>S</div>
				<div>T</div>
				<div>U</div>
				<div>V</div>
				<div>W</div>
				<div>X</div>
				<div>Y</div>
				<div>Z</div>
			</div>
			<div className="b1">
				<div className="b1-top"></div>
				<div className="b1-content">
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>祖玛珑</span><br/>
							<span>Jo Malone</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>祖玛珑</span><br/>
							<span>Jo Malone</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>祖玛珑</span><br/>
							<span>Jo Malone</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>祖玛珑</span><br/>
							<span>Jo Malone</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>祖玛珑</span><br/>
							<span>Jo Malone</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>祖玛珑</span><br/>
							<span>Jo Malone</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>祖玛珑</span><br/>
							<span>Jo Malone</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>祖玛珑</span><br/>
							<span>Jo Malone</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					<div>
						<div>
						</div>
						<div>
							<span>爱马仕</span><br/>
							<span>Hermes</span>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		)
	}
}
